title: Tkvtv
description: My Personal Blog
author: takagotch
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/takagotch
about: Freelance developer

baseurl: "/page100"
url: "https://takagotch.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: takagotch
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


